[FileDialog]
history=file:///home/dan, file:///home/dan/Downloads, file:///home/dan/.config/swhkd, file:///home/dan/Projects/AEG/VisionPortalsClient.git/task/V50-8037, file:///home/dan/Projects/AEG/VisionClient.git/feature/V50-7997
lastVisited=file:///home/dan/Downloads
qtVersion=6.8.3
shortcuts=file:, file:///home/dan
sidebarWidth=90
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xb2\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xe1\0\0\0\x1\0\0\0\0\0\0\0\x38\0\0\0\x1\0\0\0\0\0\0\0\x38\0\0\0\x1\0\0\0\0\0\0\0\x61\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0)
viewMode=List
