name: Auto Tag Version

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    
    - name: Bump version and push tag
      id: autotag
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
        RELEASE_BRANCHES: development
        WITH_V: true
    
    - name: Create Release
      if: steps.autotag.outputs.new_tag
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.autotag.outputs.new_tag }}
        release_name: ${{ steps.autotag.outputs.new_tag }}
        draft: false
        prerelease: false
